baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'olidroide 📱 Lead Software Engineer @cheerfy'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "olidroide"
  meta_og_type: "website"
  meta_og_url: "https://olidroide.es"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "olidroide 📱Lead Software Engineer @cheerfy 🕺 Continuous Bollywood Dancer 🎸 Guitar Driven Development"
  meta_twitter_card: "summary"
  meta_twitter_site: "@olidroide"
  meta_twitter_creator: "@olidroide"

collections:
  services:
    output: true
  team:
    output: false

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
